// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtlbmHzNTVvWihNOO7BWlotp77ema__O8',
    appId: '1:1019269797172:web:627e55797c9569db30c161',
    messagingSenderId: '1019269797172',
    projectId: 'lewisalpha-e23f7',
    authDomain: 'lewisalpha-e23f7.firebaseapp.com',
    storageBucket: 'lewisalpha-e23f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATYdIO5zfsfTBFNlwuQ1N2g9GwiXTiRlM',
    appId: '1:1019269797172:android:a65ce8d785b62fee30c161',
    messagingSenderId: '1019269797172',
    projectId: 'lewisalpha-e23f7',
    storageBucket: 'lewisalpha-e23f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgtS3ddF0tbMz_kW3UjehJ_lsC1xOGzZs',
    appId: '1:1019269797172:ios:d95fc481f1a5425b30c161',
    messagingSenderId: '1019269797172',
    projectId: 'lewisalpha-e23f7',
    storageBucket: 'lewisalpha-e23f7.appspot.com',
    iosBundleId: 'com.example.lewisAlpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgtS3ddF0tbMz_kW3UjehJ_lsC1xOGzZs',
    appId: '1:1019269797172:ios:455abe659f8f571230c161',
    messagingSenderId: '1019269797172',
    projectId: 'lewisalpha-e23f7',
    storageBucket: 'lewisalpha-e23f7.appspot.com',
    iosBundleId: 'com.example.lewisAlpha.RunnerTests',
  );
}
